# Generated by Django 5.1.4 on 2024-12-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweet',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
